/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ui_UIController */

#ifndef _Included_ui_UIController
#define _Included_ui_UIController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ui_UIController
 * Method:    kbHit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ui_UIController_kbHit
  (JNIEnv *, jobject);

/*
 * Class:     ui_UIController
 * Method:    getChar
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_ui_UIController_getChar
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
